// Compiles the portable metaagent library into the MetaAgentPlugin module.
#include "../../../metaagent/src/metaagent/initialize.cpp"
#include "../../../metaagent/src/metaagent/core/types.cpp"
#include "../../../metaagent/src/metaagent/core/math.cpp"
#include "../../../metaagent/src/metaagent/core/log_sink.cpp"
#include "../../../metaagent/src/metaagent/particle/forming_types.cpp"
#include "../../../metaagent/src/metaagent/particle/return_types.cpp"
#include "../../../metaagent/src/metaagent/particle/pattern_types.cpp"
#include "../../../metaagent/src/metaagent/particle/representation_types.cpp"
#include "../../../metaagent/src/metaagent/particle/transition_graph.cpp"
#include "../../../metaagent/src/metaagent/particle/forming_solver.cpp"
#include "../../../metaagent/src/metaagent/particle/actuation_math.cpp"
#include "../../../metaagent/src/metaagent/particle/shape_types.cpp"
#include "../../../metaagent/src/metaagent/particle/shape_builder.cpp"
#include "../../../metaagent/src/metaagent/particle/image_mask_processor.cpp"
#include "../../../metaagent/src/metaagent/particle/scheduler.cpp"
